### ISSUE TITLE
install Bower, and install install required libraries with Bower

### ISSUE THREAD

**Issue by maxlinux2000** [shenzhuxi/readiator#2]
Hi 
I thinks that there is an error in the readme at:
"install Bower, and install **install** required libraries with Bower"

I have tried to use "bower install"
and to the end there is this error:
`
bower material-design-icons#*     invalid-meta material-design-icons is missing "main" entry in bower.json
bower material-design-icons#*     invalid-meta material-design-icons is missing "ignore" entry in bower.json
`

then when i run "gulp" another error:
`
$ gulp
[02:03:17] Working directory changed to ~/XDK/Biblia/Readiator/readiator
[02:03:23] Using gulpfile ~/XDK/Biblia/Readiator/readiator/gulpfile.js
[02:03:23] Starting 'default'...
[02:03:23] Starting 'cordova'...
[02:03:23] Finished 'cordova' after 61 ms
[02:03:23] Starting 'chrome'...
[02:03:23] Finished 'default' after 84 ms
[02:03:23] Finished 'chrome' after 52 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error: File not found with singular glob: /home/max/test/Readiator/readiator/src/bower_components/material-design-lite/material.min.css
    at DestroyableTransform.<anonymous> (/home/max/test/node_modules/gulp-useref/lib/streamManager.js:90:36)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at emitOne (events.js:82:20)
    at Through2.emit (events.js:169:7)
    at OrderedStreams.<anonymous> (/home/max/test/node_modules/glob-stream/index.js:138:20)
    at emitOne (events.js:77:13)
    at OrderedStreams.emit (events.js:169:7)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)

`

my system is ubuntu 14.04 64bit
$ cordova -v
6.0.0
$ npm -v
3.7.2
$ bower -v
1.7.7
$ gulp -v
[02:18:22] CLI version 3.9.1
[02:18:22] Local version 3.9.1

any idea how to fix it?
bye
MaX

**Comment by shenzhuxi** [comment]
Thanks. I just fixed README.md. 
I just tried bower install and gulp and found "invalid-meta" but not any error. 

npm 3.8.5
bower 1.7.7
gulp 3.9.1
